name:                lazy-tis100
version:             0.1.0.0
github:              "githubuser/lazy-tis100"
license:             MIT
author:              "Benjamin Koch"
maintainer:          "example@example.com"
copyright:           "2022 Benjamin Koch"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/lazy-tis100#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- attoparsec
- transformers
- mtl
- neat-interpolation
- text
- generic-data
- generic-functor

ghc-options:
  - -Wall
  - -Wno-unused-imports
  - -Wno-name-shadowing
  - -Wno-unused-matches
  - -Wno-missing-signatures
  - -Wno-unused-top-binds

library:
  source-dirs: src

executables:
  lazy-tis100-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazy-tis100

tests:
  lazy-tis100-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lazy-tis100
    - hspec
    - HUnit
    - QuickCheck
